### ISSUE TITLE
Parameter Dropdown

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#13]
Although units are noted in the map legend, it would make things easier for users if the units were included in the dropdown. For example: Total heat demand (GWh)

**Comment by xrmitchell** [comment]
Some other sensible suggestions by @VT-UKPN 
“Total heat demand” and “heat demand” (first two items on drop down list) read very similar and may not be easy to differentiate by the users – suggest to supplement “heat demand” as something along the line “Heat demand (buildings in 2020)” or “Baseline heat demand”

Heading “Heating demand” to rephrase as “Heating demand (by fuel types)”, and to remove the pre-fix “met by” for items below, i.e. simplify the items to “Fossil fuel”, “Biomass” etc.

Heading “Fuel bill” - Add “annual” to specify the time period covered 

Heading “LCH uptake” – the public may not know what LCH stands for, suggest to expand the heading to “Low carbon heating technologies” or “Low carbon heating deployment”

**Comment by gilesdring** [comment]
Broadly OK - relatively simple changes. Note the following:

* This increases word count in dropdowns, so we'll need to review once done to check it's still usable.
* Adding units in "Total heat demand" may be dependent on order of magintude (e.g. GWh, TWh, etc), and may be misleading if the title suggests GWh but the numbers end to scaling to TWh
* Assume that 'Fuel bill' refers to both fuel bills.

**Comment by slowe** [comment]
@xrmitchell As Giles notes, there is going to be inconsistency between "GWh" in the drop-down and GWh/TWh/PWh in the colour scale. So I've opted for the non-prefixed SI units (Wh) instead.
