### ISSUE TITLE
Electricity demand for heat shows 0 in 2050 under Leading the Way

### ISSUE THREAD

**Issue by VT-UKPN** [odileeds/ukpn-heat-street#14]
![image](https://user-images.githubusercontent.com/71830976/124282593-e8809f00-db42-11eb-99cc-9010be24cf4f.png)

**Comment by gilesdring** [comment]
@slowe To take a look at this.

**Comment by slowe** [comment]
@VT-UKPN The problem was an inconsistent column heading in the original data packs. I've manually corrected this and re-built the data. Could you check that it looks sensible?

**Comment by VT-UKPN** [comment]
It works now. Thanks!
