### ISSUE TITLE
General page layout

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#15]
I had a session with my team yesterday to go through the map and get their feedback. We came up with a plan for how we think the page layout could be improved:
- The little preamble at the top -- make it stand out more, and change the text to also include something like 'for more info on this, please scroll down'. Preamble to also include a mention of DFES
- Add some kind of arrow to suggest that people should scroll down. Unless you really are looking, it isn't obvious that there is anything beneath the map
- Below the map, remove the copy that is there now, and replace with the following:
     - A Q&A/FAQ section (we will prepare this)
     - A link to DFES and an explanation of how these are different (possibly part of the Q&A)
     - A feedback/questions box (or prompt to email innovation@ukpowernetworks.co.uk if that isn't possible)
     - Include link to our additional analysis on bill impact slide pack (not yet published on our website but it will be soon)

**Comment by xrmitchell** [comment]
Some other things to add/modify:
- Need more warnings around customer bill impact and underlying assumptions
- Make the data assumptions/links to the data packs and reports more visible
- Better intro/reference/explanation of DFES

**Comment by gilesdring** [comment]
Let us know when you've written the content for the preamble, bottom section and any updates. Propose that we show you where this can be edited in the repo to enable you to be more agile in making changes / corrections. @slowe or @gilesdring can support.

Ref making things more prominent - perhaps would be good to discuss how this would look.

**Comment by xrmitchell** [comment]
•	Why does this map only show data for the years 2030 and 2050?
To create detailed the most detailed insights possible, heat street specifically focused only on how the energy system might change in the next ten years (2030) and by the Government’s Net Zero target (2050). However, we do published detailed yearly forecasts as part of our Distribution Future Energy Scenarios research. You can view our DFES here.

•	What is the source of the data presented on this map? Can I access it?
We use a wide range of sources and government databases for this research. This include the Energy Performance Certificate (EPC) database and the English Housing Condition Survey. All of our data is publically available on this page. 

•	What are your underlying assumptions in the data and how have you approached modelling?
We created both a housing stock model based on a wide range of data sources and a techno-economic model which forecasts how energy efficiency measures and low carbon heating systems could be used. You can view our project methodology and all of our sources in full on page 4 of our project report, here. 

•	How did you choose the different scenarios?
We based our modelled scenarios on Distribution Future Energy Scenarios, which is similar but wider-scope forecasting research which we publish annually. We also built our scenarios to be in line with industry-wide forecasting efforts such as National Grid’s Future Energy Scenarios (FES) research. (Future Energy Scenarios | National Grid ESO)

•	Why didn’t you conduct your analysis for all of the UK? 
Our license areas only cover London, the South East and East of England, so we focused our research specifically on our patch. Our area is very diverse and includes many different properties and communities, so we believe there may be some broad trends that could be consistent nationwide.

**Comment by xrmitchell** [comment]
we are happy that this is all complete and required modifications have been made
