### ISSUE TITLE
View by dropdowns

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#17]
We know that many many people still don't know what LSOAs are. Suggestion was that for each area in the 'view by' dropdown has a little grey box appear just like the parameter and scenario dropdowns, to include a short description of each.

**Comment by slowe** [comment]
I suggest changing the drop-down text from "LSOA" to "Small areas (LSOAs)".

**Comment by xrmitchell** [comment]
I think that works, good suggestion @slowe
