### ISSUE TITLE
year slider

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#18]
Having discussed it with the team, we propose removing years 2021-2029 and 2031-2049 for the new build projections, so that we can simplify the year slider to make it obvious that 2020, 2030 and 2050 are the only years you can look at. 

We will discuss with the DFES team incorporating the new build projections. We don't think it adds value to this overall visualisation to include the extra years.

**Comment by slowe** [comment]
@xrmitchell I've removed the years 2021-29 and 2031-49. If you are happy with the result you can close this.

**Comment by xrmitchell** [comment]
is it possible to move the small mid-year lines between the three key years? Even though you can't slide to them, they make it seem like you should be able to.

**Comment by slowe** [comment]
I'll look at not selecting 2020 for fuel types.

**Comment by xrmitchell** [comment]
Could you add a little bit more space between the view by and select year sections? It looks a bit odd with the existing white space layout. 
![image](https://user-images.githubusercontent.com/86667393/127479548-82947727-b64c-48de-8713-a2ec7aa79002.png)
