### ISSUE TITLE
Tracking usage of the site

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#19]
We are keen to be able to track the usage of this site to see how many people are accessing it + some additional analytics if possible. 

We use a third party app called hotjar, would it be possible to install it on this page? If not -- what are our options?

**Comment by gilesdring** [comment]
In simple terms, we can probably add it. However, a couple of points:

* You already have Google Analytics on the page - could that provide the info you need?
* If now can you be clear about the intent behind collecting the data - we've done some work on collecting click stats on pages (menu selections, etc) in a privacy protecting manner. We would be happy to provide you access to this.
* You'd need to review the company-wide privacy policy and cookie policy that we link to (or provide an alternative) as this doesn't seem to mention hotjar at the moment.

**Comment by xrmitchell** [comment]
Hi @gilesdring thanks for the tip on hotjar missing from the company-wide privacy policy. We will get that sorted. 

It sounds like the things you are tracking already through Google Analytics are exactly what we are looking for. If you are happy to provide access to this, then that meets our needs and I can close the ticket. The email address we use for all Google Analytics tracking is electricvehiclesukpn@gmail.com if it is a simple case of adding it.

**Comment by gilesdring** [comment]
I think this is a UKPN Google Analytics account - we don't run GA ourselves - @ash001j Should be able to help with this.

**Comment by xrmitchell** [comment]
I think this is complete now based on my discussion with @ash001j
