### ISSUE TITLE
Blurb for fuel bills

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#20]
For the text in the grey box that comes up under the fuel bill selection, please can you add a sentence that says 'change in fuel bills over time is influenced by energy efficiency deployment and adoption of low carbon heating technology'

My team pointed out that if we don't say something like that, people may be wondering why the fuel bills are changing.

**Comment by slowe** [comment]
@xrmitchell This sentence has been added to the parameter descriptions for all the fuel bill parameters. If you are happy with it you can close this issue.

**Comment by xrmitchell** [comment]
looks good to me
