### ISSUE TITLE
colour scale radio button

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#21]
Please can we add some text around the colour scale radio button to explain? Testing it on my colleagues, it wasn't intuitive for any of them, so I think it could also be a struggle for external stakeholders

**Comment by gilesdring** [comment]
Could you suggest some text that would make it clearer? Maybe "in year" vs "all years".

**Comment by xrmitchell** [comment]
Colour scales
To compare data across years, please select ‘by 2050’. This means that the colour scales will stay the same for each year. 
If looking at data for one specific year, please select ‘In year’. This means that the colour scales will automatically re-adjust to show the best granularity for the data in a given year

**Comment by xrmitchell** [comment]
I got some feedback from our comms team who have come up with an even better way of doing this: 
Automatically adjust colour scale? 

Yes ........ No

Then some text below:

Yes: select this and the colour scale will automatically adjust to better visualise the % differences for the specific year you have selected
No: select this and the colour scale will stay the same for each year, showing the % differences when compared to how the area will look 2050. 

So ‘yes’ is instead of ‘in year’, and ‘no’ is instead of ‘by 2050’.

**Comment by slowe** [comment]
@xrmitchell Let's update this next week.
