### ISSUE TITLE
Heating demand summary

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#23]
It would be really nice if we could add a heating demand summary to show the majority technology per area and then, when you over over it, a pie chart which shows the breakdown of other heating technology

Is this feasible?

**Comment by gilesdring** [comment]
Potentially - although I think we could do with discussing with you to understand how that might work. There issues with presenting a new derived parameter which is categorical in nature as this is not how the visualisation is built to date.

**Comment by xrmitchell** [comment]
Let's talk about this in our next session

**Comment by xrmitchell** [comment]
I have the raw data for this and can make it available for anyone who is curious. We will not add it to the map.
