### ISSUE TITLE
units

### ISSUE THREAD

**Issue by xrmitchell** [odileeds/ukpn-heat-street#25]
@slowe I got some feedback from my final approver about the PWh...it is a very unusual unit for people. Is it possible to force the system to go to TWh even for the larger numbers? I tend to agree that people will find 1,35=00 TWh easier to understand than 1.3 PWh. 

If not, I can add a FAQ explaining it - but thought I'd check just in case.

**Comment by slowe** [comment]
Should be updated as of commit 4cfac8977d2cb05b72a0a7d1d57bedfba5e7c93d

**Comment by xrmitchell** [comment]
thank you!
