### ISSUE TITLE
Typos in data packs

### ISSUE THREAD

**Issue by slowe** [odileeds/ukpn-heat-street#7]
Whilst looking through the data packs I found a few typos:

- [ ] Pack 1 sheet 2 says "...excluded here to isolate the effect the energy efficiency"
- [ ] Pack 1 sheet 5 says "energy efifiency"
- [ ] Pack 3 1A "includes the both the fuel poor" has an extra "the"
- [ ] Pack 4 LCH Uptake has "Consumer Transormation" as the scenario name

**Comment by xrmitchell** [comment]
noted. These have been changed in our versions of the documents, but we will not update the externally published versions as I don't think people will notice them and it would require changing all the hyperlinks.
