### ISSUE TITLE
Graphs showing TWh lower than MWh

### ISSUE THREAD

**Issue by VT-UKPN** [odileeds/ukpn-heat-street#9]
![image](https://user-images.githubusercontent.com/71830976/123810530-6138ee80-d8ea-11eb-9abd-fa167a7924b6.png)

**Comment by slowe** [comment]
The logic in the formatting code was wrong. The input data is "kWh" so it now uses the following logical checks:

- ≥1e9 → divides by 1e9 and uses "PWh" (petawatt hours)
- < 1e9 and ≥1e6 → divides by 1e6 and uses "TWh" (terawatt hours)
-  <1e6 and ≥1e3 → divides by 1e3 and uses "MWh" (megawatt hours)
